# Generated by Django 5.1 on 2024-08-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (0, 'Customer')], default=0),
        ),
    ]
